name: coinecta-vesting-infra
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "45432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
  coinecta-vesting-sync:
    image: coinecta-vesting-sync
    container_name: coinecta-vesting-sync
    env_file:
      - .env
    volumes:
      - /tmp:/ipc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres

  coinecta-vesting-api:
    image: coinecta-vesting-api
    container_name: coinecta-vesting-api
    ports:
      - "1337:8080"
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
  
  vesting-submit-api:
    container_name: vesting-submit-api
    image: ghcr.io/blinklabs-io/tx-submit-api:0.17.5
    restart: unless-stopped
    volumes:
      - /tmp/mainnet-node.socket:/node-ipc/node.socket
    environment:
      - CARDANO_NETWORK=mainnet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vesting-mpf-api:
    container_name: vesting-mpf-api
    image: coinecta-mpf-api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
