name: coinecta-infra
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "35432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  coinecta-sync:
    image: coinecta-sync
    container_name: coinecta-sync
    env_file:
      - .env
    volumes:
      - /tmp:/ipc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres

  coinecta-api:
    image: coinecta-api
    container_name: coinecta-api
    env_file:
      - .env
    volumes:
      -  /tmp:/ipc
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - coinecta-sync
      - postgres

  coinecta-catcher:
    image: coinecta-catcher
    container_name: coinecta-catcher
    env_file:
      - .env
    volumes:
      - ./data/cardano/ipc:/ipc
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - coinecta-api
      - cardano-submit-api

  cardano-submit-api:
    container_name: cardano-submit-api
    image: ghcr.io/blinklabs-io/tx-submit-api:0.17.5
    restart: unless-stopped
    volumes:
      - /home/rawriclark/CardanoPreview/pool/txpipe/relay1/ipc:/node-ipc
    environment:
      - CARDANO_NETWORK=preview
    ports:
      - "8090:8090"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"